version: '3'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=3001
      - OPENAI_KEY=YOUR KEY
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000